# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/betacraft/yaag"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-github"

[[constraint]]
  name = "github.com/iris-contrib/middleware"
  version = "10.0.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.0.0"

[[constraint]]
  name = "github.com/kataras/iris"
  version = "10.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.9.3"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/RichardKnop/machinery"
  version = "1.0.14"
